% %IMPORT MTi
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/guth/Dropbox/Projects/bailey-slam/trunk/ekfslam_v2/v2/StPereDataset/_040825_1735_MTi.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/11/19 15:05:24

%% Initialize variables.
filename = '/StPereDataset/_040825_1735_MTi.log';
delimiter = '\t';
startRow = 6;

%% Format string for each line of text:
%   column1: double (%f)
%	column5: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%f%*s%*s%*s%f%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
MTiLogTime = dataArray{:, 1};
MTiYaw = dataArray{:, 2};
MTiVelYaw = dataArray{:, 3};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


%IMPORT DVL
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/guth/Dropbox/Projects/bailey-slam/trunk/ekfslam_v2/v2/StPereDataset/_040825_1735_DVL.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/11/19 15:06:33

%% Initialize variables.
filename = '/StPereDataset/_040825_1735_DVL.log';
delimiter = {'\t',' '};
startRow = 5;

%% Format string for each line of text:
%   column1: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
DVLlogTime = dataArray{:, 1};
DVLwaterVelX = dataArray{:, 2};
DVLwaterVelY = dataArray{:, 3};
DVLwaterVelZ = dataArray{:, 4};
DVLwaterStatus = dataArray{:, 5};
DVLbottomVelX = dataArray{:, 6};
DVLbottomVelY = dataArray{:, 7};
DVLbottomVelZ = dataArray{:, 8};
DVLbottomStatus = dataArray{:, 9};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/guth/Dropbox/Projects/bailey-slam/trunk/ekfslam_v2/v2/StPereDataset/_040825_1735_IS.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/11/29 17:43:49